/**
 * 爬虫模板管理类
 * 提供模板验证、导入导出、测试等功能
 */

import { v4 as uuidv4 } from 'uuid';
import { TemplateAnalyzer, AnalyzedTemplate } from './TemplateAnalyzer';

export interface CrawlerTemplateData {
  id?: string;
  userId: string;
  name: string;
  description?: string;
  url: string;
  pageType?: 'static' | 'dynamic';
  department?: string;
  dataType?: string;
  containerSelector: string;
  fields: { name: string; selector: string }[];
  autoGenerated?: boolean;
  tags?: string[];
  confidence?: number;
  // 分页配置
  paginationEnabled?: boolean;
  paginationNextSelector?: string;
  paginationMaxPages?: number;
}

export interface TemplateTestResult {
  success: boolean;
  dataCount: number;
  sampleData: any[];
  errors: string[];
  warnings: string[];
}

export interface TemplateExport {
  version: string;
  exportedAt: string;
  template: CrawlerTemplateData;
}

export class CrawlerTemplate {
  /**
   * 验证模板数据
   */
  static validate(template: CrawlerTemplateData): {
    valid: boolean;
    errors: string[];
    warnings: string[];
  } {
    const errors: string[] = [];
    const warnings: string[] = [];

    // 必填字段验证
    if (!template.userId) errors.push('缺少用户ID');
    if (!template.name?.trim()) errors.push('模板名称不能为空');
    if (!template.url?.trim()) errors.push('URL不能为空');

    // URL格式验证
    try {
      new URL(template.url);
    } catch {
      errors.push('URL格式不正确');
    }

    // 选择器验证
    if (!template.containerSelector?.trim()) {
      errors.push('容器选择器不能为空');
    }

    if (!template.fields || template.fields.length === 0) {
      errors.push('至少需要一个字段');
    } else {
      // 验证字段配置
      const fieldNames = new Set<string>();
      for (const field of template.fields) {
        if (!field.name?.trim()) {
          errors.push('字段名称不能为空');
        }
        if (!field.selector?.trim()) {
          errors.push(`字段"${field.name}"的选择器不能为空`);
        }
        if (fieldNames.has(field.name)) {
          warnings.push(`字段名称"${field.name}"重复`);
        }
        fieldNames.add(field.name);
      }
    }

    // 推荐检查
    const hasTitle = template.fields?.some(f => f.name === '标题');
    const hasLink = template.fields?.some(f => f.name === '链接');

    if (!hasTitle) warnings.push('建议添加"标题"字段');
    if (!hasLink) warnings.push('建议添加"链接"字段');

    return {
      valid: errors.length === 0,
      errors,
      warnings
    };
  }

  /**
   * 格式化模板（确保数据完整）
   */
  static format(template: CrawlerTemplateData): CrawlerTemplateData {
    return {
      id: template.id || uuidv4(),
      userId: template.userId,
      name: template.name.trim(),
      description: template.description?.trim() || '',
      url: template.url.trim(),
      pageType: template.pageType || 'static',
      department: template.department?.trim(),
      dataType: template.dataType?.trim() || '政策文件',
      containerSelector: template.containerSelector.trim(),
      fields: template.fields.map(f => ({
        name: f.name.trim(),
        selector: f.selector.trim()
      })),
      autoGenerated: template.autoGenerated || false,
      tags: template.tags || [],
      confidence: template.confidence || 100
    };
  }

  /**
   * 导出模板为JSON
   */
  static exportToJson(template: CrawlerTemplateData): string {
    const exportData: TemplateExport = {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      template: this.format(template)
    };

    return JSON.stringify(exportData, null, 2);
  }

  /**
   * 从JSON导入模板
   */
  static importFromJson(json: string): CrawlerTemplateData {
    try {
      const data: TemplateExport = JSON.parse(json);

      if (!data.template) {
        throw new Error('无效的模板文件格式');
      }

      return {
        ...data.template,
        id: undefined, // 导入时生成新ID
        userId: data.template.userId // 需要更新为当前用户ID
      };
    } catch (error) {
      throw new Error(`导入失败: ${error instanceof Error ? error.message : '未知错误'}`);
    }
  }

  /**
   * 批量导入模板
   */
  static async importBatch(
    templates: CrawlerTemplateData[],
    userId: string,
    saveFn: (template: CrawlerTemplateData) => Promise<string>
  ): Promise<{
    success: number;
    failed: number;
    results: Array<{ name: string; success: boolean; error?: string }>;
  }> {
    const results = [];

    for (const tpl of templates) {
      try {
        // 验证模板
        const validation = this.validate(tpl);
        if (!validation.valid) {
          results.push({
            name: tpl.name,
            success: false,
            error: validation.errors.join(', ')
          });
          continue;
        }

        // 格式化并保存
        const formatted = this.format({
          ...tpl,
          userId // 使用当前用户ID
        });

        await saveFn(formatted);
        results.push({ name: tpl.name, success: true });
      } catch (error: any) {
        results.push({
          name: tpl.name,
          success: false,
          error: error.message || '未知错误'
        });
      }
    }

    return {
      success: results.filter(r => r.success).length,
      failed: results.filter(r => !r.success).length,
      results
    };
  }

  /**
   * 批量导出模板
   */
  static exportBatch(templates: CrawlerTemplateData[]): string {
    const exportData = {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      count: templates.length,
      templates: templates.map(t => this.format(t))
    };

    return JSON.stringify(exportData, null, 2);
  }

  /**
   * 从AnalyzedTemplate转换
   */
  static fromAnalyzed(analyzed: AnalyzedTemplate, userId: string): CrawlerTemplateData {
    return {
      userId,
      name: analyzed.name,
      url: analyzed.url,
      pageType: analyzed.pageType,
      containerSelector: analyzed.containerSelector,
      fields: analyzed.fields,
      autoGenerated: analyzed.metadata.autoGenerated,
      tags: analyzed.metadata.suggestedTags,
      confidence: analyzed.confidence
    };
  }

  /**
   * 测试模板（模拟运行，不保存数据）
   */
  static async test(
    template: CrawlerTemplateData,
    testFn: (url: string, selectors: any) => Promise<any>
  ): Promise<TemplateTestResult> {
    const errors: string[] = [];
    const warnings: string[] = [];

    // 验证模板
    const validation = this.validate(template);
    if (!validation.valid) {
      return {
        success: false,
        dataCount: 0,
        sampleData: [],
        errors: validation.errors,
        warnings: validation.warnings
      };
    }

    warnings.push(...validation.warnings);

    // 构建选择器配置
    const selectors: any = {
      container: template.containerSelector,
      fields: {}
    };

    for (const field of template.fields) {
      selectors.fields[field.name] = field.selector;
    }

    try {
      // 执行测试
      const result = await testFn(template.url, selectors);

      if (result.success) {
        const dataCount = result.data?.length || 0;

        if (dataCount === 0) {
          warnings.push('未提取到任何数据，请检查选择器配置');
        }

        return {
          success: true,
          dataCount,
          sampleData: result.data?.slice(0, 5) || [], // 只返回前5条作为示例
          errors: [],
          warnings
        };
      } else {
        return {
          success: false,
          dataCount: 0,
          sampleData: [],
          errors: [result.error || '数据提取失败'],
          warnings
        };
      }
    } catch (error: any) {
      return {
        success: false,
        dataCount: 0,
        sampleData: [],
        errors: [error.message || '测试执行失败'],
        warnings
      };
    }
  }

  /**
   * 克隆模板（用于用户复制系统模板）
   */
  static clone(template: CrawlerTemplateData, newUserId: string): CrawlerTemplateData {
    return {
      ...template,
      id: undefined, // 生成新ID
      userId: newUserId,
      name: `${template.name} (副本)`,
      autoGenerated: false // 复制的模板不算自动生成
    };
  }

  /**
   * 合并模板更新
   */
  static merge(
    original: CrawlerTemplateData,
    updates: Partial<CrawlerTemplateData>
  ): CrawlerTemplateData {
    return {
      ...original,
      ...updates,
      id: original.id, // 保持原ID
      userId: original.userId, // 保持原用户ID
      fields: updates.fields || original.fields
    };
  }

  /**
   * 生成模板摘要（用于列表显示）
   */
  static summarize(template: CrawlerTemplateData): {
    name: string;
    url: string;
    fieldCount: number;
    pageType: string;
    autoGenerated: boolean;
    tags: string[];
  } {
    return {
      name: template.name,
      url: template.url,
      fieldCount: template.fields?.length || 0,
      pageType: template.pageType || 'static',
      autoGenerated: template.autoGenerated || false,
      tags: template.tags || []
    };
  }

  /**
   * 检查模板兼容性
   */
  static checkCompatibility(template: CrawlerTemplateData): {
    compatible: boolean;
    issues: string[];
  } {
    const issues: string[] = [];

    // 检查选择器语法
    try {
      // 简单的CSS选择器语法检查
      if (template.containerSelector) {
        if (template.containerSelector.includes('::')) {
          // 不支持伪元素（Python引擎支持，但需要特殊处理）
          if (!template.containerSelector.includes('::attr')) {
            issues.push('容器选择器不应包含伪元素');
          }
        }
      }

      for (const field of template.fields) {
        if (field.selector.includes('::')) {
          if (!field.selector.includes('::attr')) {
            issues.push(`字段"${field.name}"使用了不支持的伪元素`);
          }
        }
      }
    } catch (error) {
      issues.push('选择器语法检查失败');
    }

    return {
      compatible: issues.length === 0,
      issues
    };
  }
}
