import type { FieldMappingSuggestion, StandardColumn } from './types';

type BuildCollectionScriptOptions = {
  projectName: string;
  standardTableName: string;
  sampleFileName: string;
  sourceFormat: string;
  standardFields: StandardColumn[];
  mapping: FieldMappingSuggestion[];
  extractionHints?: string[];
};

function pyString(value: string): string {
  return JSON.stringify(value);
}

export function buildCollectionScript(options: BuildCollectionScriptOptions): string {
  const mappingDict = options.mapping
    .filter((item) => item.confidence >= 0.6)
    .reduce<Record<string, string>>((acc, item) => {
      acc[item.sourceHeader] = item.standardField;
      return acc;
    }, {});

  const standardFields = options.standardFields.map((field) => field.title);
  const hints = options.extractionHints || [];

  return [
    '#!/usr/bin/env python3',
    'import argparse',
    'import csv',
    'import json',
    'import os',
    'import re',
    'import sys',
    'from typing import Dict, List, Any',
    '',
    `PROJECT_NAME = ${pyString(options.projectName)}`,
    `STANDARD_TABLE_NAME = ${pyString(options.standardTableName)}`,
    `SAMPLE_FILE_NAME = ${pyString(options.sampleFileName)}`,
    `SOURCE_FORMAT = ${pyString(options.sourceFormat)}`,
    `STANDARD_FIELDS = json.loads(${pyString(JSON.stringify(standardFields))})`,
    `FIELD_MAPPING = json.loads(${pyString(JSON.stringify(mappingDict))})`,
    `EXTRACTION_HINTS = json.loads(${pyString(JSON.stringify(hints))})`,
    '',
    'def normalize_text(value: str) -> str:',
    '    return re.sub(r"[^0-9a-zA-Z\\u4e00-\\u9fa5]+", "", (value or "").strip().lower())',
    '',
    'def resolve_field_name(source_header: str) -> str:',
    '    if source_header in FIELD_MAPPING:',
    '        return FIELD_MAPPING[source_header]',
    '    normalized_header = normalize_text(source_header)',
    '    for candidate, target in FIELD_MAPPING.items():',
    '        if normalize_text(candidate) == normalized_header:',
    '            return target',
    '    return source_header',
    '',
    'def finalize_records(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:',
    '    finalized = []',
    '    for record in records:',
    '        normalized = {field: "" for field in STANDARD_FIELDS}',
    '        for key, value in record.items():',
    '            target = resolve_field_name(key)',
    '            if target in normalized:',
    '                normalized[target] = "" if value is None else value',
    '        finalized.append(normalized)',
    '    return finalized',
    '',
    'def read_csv_file(file_path: str) -> List[Dict[str, Any]]:',
    '    with open(file_path, "r", encoding="utf-8-sig", errors="ignore", newline="") as handle:',
    '        reader = csv.DictReader(handle)',
    '        return [dict(row) for row in reader]',
    '',
    'def read_excel_file(file_path: str) -> List[Dict[str, Any]]:',
    '    try:',
    '        from openpyxl import load_workbook',
    '    except ImportError as exc:',
    '        raise RuntimeError("openpyxl is required for Excel collection") from exc',
    '',
    '    workbook = load_workbook(file_path, read_only=True, data_only=True)',
    '    sheet = workbook[workbook.sheetnames[0]]',
    '    rows = list(sheet.iter_rows(values_only=True))',
    '    workbook.close()',
    '    if not rows:',
    '        return []',
    '    headers = [str(item).strip() if item is not None else "" for item in rows[0]]',
    '    records = []',
    '    for row in rows[1:]:',
    '        record = {}',
    '        for index, header in enumerate(headers):',
    '            if not header:',
    '                continue',
    '            value = row[index] if index < len(row) else ""',
    '            record[header] = value',
    '        if record:',
    '            records.append(record)',
    '    return records',
    '',
    'def read_docx_file(file_path: str) -> List[Dict[str, Any]]:',
    '    try:',
    '        from docx import Document',
    '    except ImportError as exc:',
    '        raise RuntimeError("python-docx is required for Word collection") from exc',
    '',
    '    document = Document(file_path)',
    '    for table in document.tables:',
    '        if not table.rows:',
    '            continue',
    '        headers = [cell.text.strip() for cell in table.rows[0].cells]',
    '        records = []',
    '        for row in table.rows[1:]:',
    '            item = {}',
    '            for index, header in enumerate(headers):',
    '                if not header:',
    '                    continue',
    '                item[header] = row.cells[index].text.strip() if index < len(row.cells) else ""',
    '            if item:',
    '                records.append(item)',
    '        if records:',
    '            return records',
    '    text = "\\n".join([paragraph.text.strip() for paragraph in document.paragraphs if paragraph.text.strip()])',
    '    return read_text_blocks(text)',
    '',
    'def read_pdf_file(file_path: str) -> List[Dict[str, Any]]:',
    '    try:',
    '        import pdfplumber',
    '    except ImportError as exc:',
    '        raise RuntimeError("pdfplumber is required for PDF collection") from exc',
    '',
    '    text_parts: List[str] = []',
    '    with pdfplumber.open(file_path) as pdf:',
    '        for page in pdf.pages:',
    '            text = page.extract_text() or ""',
    '            if text.strip():',
    '                text_parts.append(text)',
    '    return read_text_blocks("\\n".join(text_parts))',
    '',
    'def read_text_blocks(text: str) -> List[Dict[str, Any]]:',
    '    blocks = [block.strip() for block in re.split(r"\\n\\s*\\n", text) if block.strip()]',
    '    records: List[Dict[str, Any]] = []',
    '    for block in blocks:',
    '        record: Dict[str, Any] = {}',
    '        for line in block.splitlines():',
    '            if ":" in line:',
    '                key, value = line.split(":", 1)',
    '                record[key.strip()] = value.strip()',
    '            elif "：" in line:',
    '                key, value = line.split("：", 1)',
    '                record[key.strip()] = value.strip()',
    '        if record:',
    '            records.append(record)',
    '    if records:',
    '        return records',
    '    joined = " ".join(text.split())',
    '    fallback = {field: "" for field in STANDARD_FIELDS}',
    '    for hint in EXTRACTION_HINTS:',
    '        if hint and hint in joined:',
    '            fallback[hint] = hint',
    '    if joined:',
    '        fallback[STANDARD_FIELDS[0] if STANDARD_FIELDS else "content"] = joined[:500]',
    '    return [fallback] if joined else []',
    '',
    'def read_txt_file(file_path: str) -> List[Dict[str, Any]]:',
    '    with open(file_path, "r", encoding="utf-8", errors="ignore") as handle:',
    '        return read_text_blocks(handle.read())',
    '',
    'def load_records(file_path: str) -> List[Dict[str, Any]]:',
    '    ext = os.path.splitext(file_path)[1].lower()',
    '    if ext == ".csv":',
    '        return read_csv_file(file_path)',
    '    if ext in (".xlsx", ".xlsm", ".xls"):',
    '        return read_excel_file(file_path)',
    '    if ext == ".docx":',
    '        return read_docx_file(file_path)',
    '    if ext == ".pdf":',
    '        return read_pdf_file(file_path)',
    '    return read_txt_file(file_path)',
    '',
    'def main() -> None:',
    '    parser = argparse.ArgumentParser()',
    '    parser.add_argument("--input", required=True)',
    '    parser.add_argument("--output")',
    '    args = parser.parse_args()',
    '',
    '    records = finalize_records(load_records(args.input))',
    '    headers = list(records[0].keys()) if records else STANDARD_FIELDS',
    '    preview_rows = records[:5]',
    '    payload = {',
    '        "projectName": PROJECT_NAME,',
    '        "standardTableName": STANDARD_TABLE_NAME,',
    '        "sampleFileName": SAMPLE_FILE_NAME,',
    '        "sourceFormat": SOURCE_FORMAT,',
        '        "headers": headers,',
    '        "recordCount": len(records),',
    '        "previewRows": preview_rows,',
    '        "records": records,',
    '    }',
    '',
    '    if args.output:',
    '        with open(args.output, "w", encoding="utf-8") as handle:',
    '            json.dump(payload, handle, ensure_ascii=False, indent=2)',
    '    else:',
    '        json.dump(payload, sys.stdout, ensure_ascii=False)',
    '',
    'if __name__ == "__main__":',
    '    main()',
    '',
  ].join('\n');
}
