/**
 * 智能爬虫模板分析器
 * 自动分析网页结构，生成选择器配置
 */

import { DynamicEngine } from './dynamic_engine';
import * as cheerio from 'cheerio';

export interface PageAnalysis {
  url: string;
  pageType: 'static' | 'dynamic';
  hasJavaScript: boolean;
  recommendations: SelectorRecommendation[];
  confidence: number;
}

export interface SelectorRecommendation {
  container: string;
  fields: Record<string, string>;
  confidence: number;
  reason: string;
}

export interface AnalyzedTemplate {
  name: string;
  url: string;
  pageType: 'static' | 'dynamic';
  containerSelector: string;
  fields: { name: string; selector: string }[];
  confidence: number;
  metadata: {
    analyzedAt: string;
    autoGenerated: true;
    suggestedTags: string[];
  };
}

/**
 * 政府网站常见结构模式
 */
const GOV_PATTERNS = {
  // 列表容器模式
  containers: [
    { selector: 'ul li', weight: 1, desc: '通用列表' },
    { selector: '.list li, .list li', weight: 2, desc: '带list类的列表' },
    { selector: '.news-list li, .newslist li', weight: 3, desc: '新闻列表' },
    { selector: '.policy-list li, .policylist li', weight: 4, desc: '政策列表' },
    { selector: 'table tr', weight: 2, desc: '表格行' },
    { selector: '.doc-list li, .doclist li', weight: 4, desc: '文档列表' },
    { selector: '[class*="list"] li', weight: 1.5, desc: '包含list的类名' },
  ],

  // 字段模式
  title: [
    'a', 'a[title]', '.title', 'h3', 'h4',
    '.news-title', '.doc-title', '.policy-title',
    '[class*="title"]'
  ],
  link: [
    'a', 'a[href]',
  ],
  date: [
    '.date', '.time', 'span[class*="date"]', 'span[class*="time"]',
    '.publish-date', '.pub-date', '.release-date',
    'font', 'span', 'time'
  ],
  source: [
    '.source', '.author', '.publisher', '[class*="source"]',
    '[class*="author"]'
  ],
  docNumber: [
    '.doc-number', '.number', '.file-number', '[class*="number"]'
  ]
};

export class TemplateAnalyzer {
  /**
   * 分析网页并生成模板建议
   */
  static async analyze(url: string, description?: string): Promise<AnalyzedTemplate> {
    console.log(`[TemplateAnalyzer] 开始分析: ${url}`);

    // 1. 智能检测页面类型并获取HTML
    let html: string;
    let pageType: 'static' | 'dynamic';

    // 先尝试静态抓取
    console.log(`[TemplateAnalyzer] 第一步：尝试静态抓取...`);
    try {
      html = await this.fetchStaticHtml(url);
      pageType = this.detectPageType(html, url);
      console.log(`[TemplateAnalyzer] 静态分析结果: ${pageType}`);

      // 如果判定为动态，切换到动态渲染
      if (pageType === 'dynamic') {
        console.log(`[TemplateAnalyzer] 第二步：切换到动态渲染...`);
        html = await DynamicEngine.fetchHtml(url);
      }
    } catch (error: any) {
      console.warn(`[TemplateAnalyzer] 静态抓取失败: ${error.message}`);
      console.log(`[TemplateAnalyzer] 使用动态渲染`);
      html = await DynamicEngine.fetchHtml(url);
      pageType = 'dynamic';
    }

    // 2. 分析HTML结构
    const $ = cheerio.load(html);
    const analysis = this.analyzeHtmlStructure($, url, pageType);

    // 4. 生成最佳推荐
    const best = this.selectBestRecommendation(analysis.recommendations);

    // 5. 构建模板
    const template: AnalyzedTemplate = {
      name: description || this.generateTemplateName(url, $),
      url,
      pageType,
      containerSelector: best.container,
      fields: Object.entries(best.fields).map(([name, selector]) => ({
        name,
        selector
      })),
      confidence: best.confidence,
      metadata: {
        analyzedAt: new Date().toISOString(),
        autoGenerated: true,
        suggestedTags: this.generateTags(url, $)
      }
    };

    console.log(`[TemplateAnalyzer] 分析完成，置信度: ${template.confidence}%`);
    return template;
  }

  /**
   * 智能检测页面类型（静态/动态）
   */
  private static detectPageType(html: string, url: string): 'static' | 'dynamic' {
    console.log(`[TemplateAnalyzer] 智能检测页面类型...`);
    return this.analyzeHtmlContent(html, url);
  }

  /**
   * 分析HTML内容判断页面类型
   */
  private static analyzeHtmlContent(html: string, url: string): 'static' | 'dynamic' {
    const $ = cheerio.load(html);

    // 1. 检测明显的JavaScript框架特征
    const hasReact = $('html').toString().includes('_react') ||
                     $('div[id^="react-"]').length > 0;
    const hasVue = $('div[data-v-]').length > 0 ||
                   $('div[data-server-rendered]').length > 0;
    const hasAngular = $('ng-app').length > 0 ||
                       $('[ng-controller]').length > 0;

    if (hasReact || hasVue || hasAngular) {
      console.log(`[TemplateAnalyzer] 检测到前端框架: ${hasReact ? 'React' : ''}${hasVue ? 'Vue' : ''}${hasAngular ? 'Angular' : ''}`);
      return 'dynamic';
    }

    // 2. 检测常见的数据容器
    const commonContainers = [
      '#resultlist', '.list', '.news-list', '.policy-list',
      'table tbody', '.content-list', '[class*="list"]'
    ];

    let containerFound = false;
    let containerEmpty = true;

    for (const selector of commonContainers) {
      const $el = $(selector);
      if ($el.length > 0) {
        containerFound = true;
        // 检查容器是否有实质内容
        const text = $el.text().trim();
        const links = $el.find('a[href]').length;

        if (text.length > 100 || links >= 3) {
          containerEmpty = false;
          break;
        }
      }
    }

    // 3. 检测是否有"加载中"或"请等待"等提示
    const loadingText = ['加载中', '请稍候', 'loading...', '数据加载中', '请等待'];
    const bodyText = $('body').text();
    if (loadingText.some(text => bodyText.includes(text))) {
      console.log(`[TemplateAnalyzer] 检测到加载提示文本`);
      return 'dynamic';
    }

    // 4. 检测是否有空的容器但有JavaScript加载脚本
    const scripts = $('script').text();
    if (scripts.includes('fetch(') || scripts.includes('axios.') || scripts.includes('$.ajax')) {
      // 有AJAX加载
      console.log(`[TemplateAnalyzer] 检测到AJAX加载`);

      // 检查列表容器是否为空
      for (const selector of commonContainers) {
        const $el = $(selector);
        if ($el.length > 0 && $el.text().trim().length < 50) {
          console.log(`[TemplateAnalyzer] 容器 ${selector} 存在但内容为空，需要动态渲染`);
          return 'dynamic';
        }
      }
    }

    // 5. 特定网站模式
    const urlPatterns = [
      { pattern: /szj\.hebei\.gov\.cn/, type: 'dynamic' as const, name: '河北数据局' },
      { pattern: /\.gov\.cn.*\/(zwgk|zhengce|policy)/, type: 'dynamic' as const, name: '政府网站政策页' },
      { pattern: /shtml$/, type: 'dynamic' as const, name: 'SHTML页面' },
      { pattern: /[?&]_=/, type: 'dynamic' as const, name: 'AJAX参数' },
    ];

    for (const { pattern, type, name } of urlPatterns) {
      if (pattern.test(url)) {
        console.log(`[TemplateAnalyzer] URL匹配: ${name}`);
        return type;
      }
    }

    // 6. 如果找不到容器或容器为空，建议动态渲染
    if (!containerFound || containerEmpty) {
      console.log(`[TemplateAnalyzer] 未找到有效容器，建议动态渲染`);
      return 'dynamic';
    }

    console.log(`[TemplateAnalyzer] 判定为静态页面`);
    return 'static';
  }

  /**
   * 获取静态HTML
   */
  private static async fetchStaticHtml(url: string): Promise<string> {
    try {
      const response = await fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
      });
      return await response.text();
    } catch (error) {
      console.error('[TemplateAnalyzer] 静态抓取失败，尝试动态渲染');
      return DynamicEngine.fetchHtml(url);
    }
  }

  /**
   * 分析HTML结构，生成候选选择器
   */
  private static analyzeHtmlStructure(
    $: cheerio.CheerioAPI,
    url: string,
    pageType: 'static' | 'dynamic'
  ): PageAnalysis {
    const recommendations: SelectorRecommendation[] = [];

    // 1. 尝试不同的列表容器
    for (const pattern of GOV_PATTERNS.containers) {
      const $container = $(pattern.selector);

      if ($container.length >= 3) { // 至少有3个项目
        // 分析容器内的字段
        const fields = this.extractFieldsFromContainer($, $container.first());

        if (Object.keys(fields).length > 0) {
          recommendations.push({
            container: pattern.selector,
            fields,
            confidence: this.calculateConfidence($container, fields, pattern.weight),
            reason: `找到${$container.length}个${pattern.desc}`
          });
        }
      }
    }

    // 2. 如果没有找到合适的列表，尝试通用模式
    if (recommendations.length === 0) {
      const fallback = this.fallbackAnalysis($);
      if (fallback) {
        recommendations.push(fallback);
      }
    }

    return {
      url,
      pageType,
      hasJavaScript: $('script').length > 0,
      recommendations,
      confidence: recommendations.length > 0
        ? Math.max(...recommendations.map(r => r.confidence))
        : 0
    };
  }

  /**
   * 从容器中提取字段选择器
   */
  private static extractFieldsFromContainer(
    $: cheerio.CheerioAPI,
    $container: cheerio.Cheerio<any>
  ): Record<string, string> {
    const fields: Record<string, string> = {};

    // 分析标题字段
    const titleSelector = this.findBestSelector($, $container, GOV_PATTERNS.title);
    if (titleSelector) {
      fields['标题'] = titleSelector;
    }

    // 分析链接字段
    const linkSelector = this.findBestSelector($, $container, GOV_PATTERNS.link);
    if (linkSelector) {
      fields['链接'] = linkSelector + '::attr(href)';
    }

    // 分析日期字段
    const dateSelector = this.findBestSelector($, $container, GOV_PATTERNS.date);
    if (dateSelector) {
      fields['发布日期'] = dateSelector;
    }

    // 分析来源字段
    const sourceSelector = this.findBestSelector($, $container, GOV_PATTERNS.source);
    if (sourceSelector) {
      fields['来源'] = sourceSelector;
    }

    // 分析文号字段
    const docNumberSelector = this.findBestSelector($, $container, GOV_PATTERNS.docNumber);
    if (docNumberSelector) {
      fields['发文字号'] = docNumberSelector;
    }

    return fields;
  }

  /**
   * 在容器内查找最佳选择器
   */
  private static findBestSelector(
    $: cheerio.CheerioAPI,
    $container: cheerio.Cheerio<any>,
    selectors: string[]
  ): string | null {
    for (const selector of selectors) {
      const $elem = $container.find(selector);
      if ($elem.length > 0 && $elem.text().trim().length > 0) {
        return selector;
      }
    }
    return null;
  }

  /**
   * 计算推荐置信度
   */
  private static calculateConfidence(
    $containers: cheerio.Cheerio<any>,
    fields: Record<string, string>,
    weight: number
  ): number {
    let score = 0;

    // 容器数量评分 (最多30分)
    const count = $containers.length;
    score += Math.min(30, count * 3);

    // 字段完整性评分 (最多50分)
    const hasTitle = !!fields['标题'];
    const hasLink = !!fields['链接'];
    const hasDate = !!fields['发布日期'];

    if (hasTitle) score += 20;
    if (hasLink) score += 15;
    if (hasDate) score += 15;

    // 模式权重 (最多20分)
    score += weight * 5;

    return Math.min(100, Math.round(score));
  }

  /**
   * 兜底分析方法
   */
  private static fallbackAnalysis($: cheerio.CheerioAPI): SelectorRecommendation | null {
    // 查找所有链接元素
    const $links = $('a[href]');
    if ($links.length < 3) return null;

    // 找到链接最多的父级元素
    let bestParent: cheerio.Cheerio<any> | null = null;
    let maxCount = 0;

    $links.each((_, el) => {
      const $parent = $(el).parent();
      const linkCount = $parent.find('a').length;

      if (linkCount > maxCount && linkCount >= 3) {
        maxCount = linkCount;
        bestParent = $parent;
      }
    });

    if (!bestParent) return null;

    return {
      container: 'a[href]', // 使用所有链接作为容器
      fields: {
        '标题': 'a[href]',
        '链接': 'a[href]::attr(href)'
      },
      confidence: 40,
      reason: '兜底方案：使用链接元素'
    };
  }

  /**
   * 选择最佳推荐
   */
  private static selectBestRecommendation(
    recommendations: SelectorRecommendation[]
  ): SelectorRecommendation {
    return recommendations.reduce((best, current) =>
      current.confidence > best.confidence ? current : best
    , recommendations[0]);
  }

  /**
   * 生成模板名称
   */
  private static generateTemplateName(url: string, $: cheerio.CheerioAPI): string {
    try {
      const urlObj = new URL(url);
      const hostname = urlObj.hostname.replace('www.', '');

      // 尝试从页面获取标题
      const title = $('title').text() || $('h1').first().text() || '';

      return title ? `${title} (${hostname})` : `${hostname} 数据采集`;
    } catch {
      return '网页数据采集模板';
    }
  }

  /**
   * 生成标签建议
   */
  private static generateTags(url: string, $: cheerio.CheerioAPI): string[] {
    const tags: string[] = [];

    try {
      const hostname = new URL(url).hostname;

      // 域名标签
      if (hostname.includes('gov.cn')) {
        tags.push('政府网站');
      }

      // 省份标签
      const provinces = [
        'beijing', 'tianjin', 'shanghai', 'chongqing',
        'hebei', 'shanxi', 'neimenggu', 'liaoning', 'jilin', 'heilongjiang',
        'jiangsu', 'zhejiang', 'anhui', 'fujian', 'jiangxi', 'shandong',
        'henan', 'hubei', 'hunan', 'guangdong', 'guangxi', 'hainan',
        'sichuan', 'guizhou', 'yunnan', 'xizang', 'shaanxi', 'gansu',
        'qinghai', 'ningxia', 'xinjiang'
      ];

      for (const p of provinces) {
        if (hostname.includes(p)) {
          tags.push(p);
          break;
        }
      }

      // 内容类型标签
      const title = $('title').text().toLowerCase();
      if (title.includes('政策') || title.includes('文件')) {
        tags.push('政策文件');
      } else if (title.includes('新闻') || title.includes('动态')) {
        tags.push('新闻动态');
      } else if (title.includes('公告') || title.includes('公示')) {
        tags.push('公告公示');
      }

    } catch (e) {
      console.error('[TemplateAnalyzer] 生成标签失败', e);
    }

    return tags.length > 0 ? tags : ['网页采集'];
  }

  /**
   * 验证模板
   */
  static async validateTemplate(template: AnalyzedTemplate): Promise<{
    valid: boolean;
    issues: string[];
  }> {
    const issues: string[] = [];

    // 验证URL
    try {
      new URL(template.url);
    } catch {
      issues.push('无效的URL');
    }

    // 验证选择器
    if (!template.containerSelector) {
      issues.push('缺少容器选择器');
    }

    if (template.fields.length === 0) {
      issues.push('没有配置任何字段');
    }

    // 验证必需字段
    const hasTitle = template.fields.some(f => f.name === '标题');
    const hasLink = template.fields.some(f => f.name === '链接');

    if (!hasTitle) issues.push('建议添加"标题"字段');
    if (!hasLink) issues.push('建议添加"链接"字段');

    return {
      valid: issues.length === 0,
      issues
    };
  }
}
